title: formsflow.ai
description: formsflow.ai installation document
theme: just-the-docs

url: https://aot-technologies.github.io/forms-flow-installation-doc

# Set a path/url to a logo that will be displayed instead of the title
logo: "./assets/logo.svg"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "./assets/logo.svg"


# Aux links for the upper right navigation
# aux_links:
#   "Docker":
#     - "https://github.com/AOT-Technologies/forms-flow-installation-doc"





